version: '3'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - '8080:8080'

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'